version: '3'

services:
  php:
    ports:
      - 8085:80
    build: 
      context: ./server
      dockerfile: Dockerfile_php
    links:
      - db
    volumes:
      - ./server:/var/www/html

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./server:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
    ports:
      - 8081:3306

volumes:
  db_volume:
