version: '3'
services:
    static_s:
        image: nginx
        container_name: nginx_main
        volumes:
            - ./php/src/style.css:/usr/share/nginx/style.css
            - ./php_for_nginx/conf/:/etc/nginx/conf.d
            - ./php/src:/usr/share/nginx
        depends_on:
            - php-apache
        ports:
            - "80:80"

    php-apache:
        container_name: php-apache_main
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/pr
            - ./php/src/private:/var/www/pr/private
            - ./php/000-default.conf:/etc/apache2/sites-available/000-default.conf
    db:
        container_name: auth_data_main
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: appDB
        volumes:
            - ./:/docker-entrypoint-initdb.d
            - db_volume:/var/lib/mysql
        ports:
            - "9906:3306"
volumes:
    db_volume:
