version: '3'

services:
  php:
    ports:
      - 8085:80
    build: 
      context: ./server
      dockerfile: Dockerfile_php
    volumes:
      - ./server:/var/www/html

volumes:
  db_volume:
